### ISSUE TITLE
编译报错：More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

### ISSUE THREAD

**Issue by RicardoJiang** [gdutxiaoxu/AnchorTask#1]
编译报错，如标题所示
可选解决方案：https://blog.csdn.net/jabony/article/details/112930562
希望能处理下

**Comment by gdutxiaoxu** [comment]
@shenzhen2017 你项目是没有使用 kotlin 嘛，方便加一下 qq 或者微信了解一下嘛，可以加一下我的微信，讨论一下

![](https://gitee.com/gdutxiaoxu/blog-picture/raw/master/21/02/20210513202941.png)

**Comment by RicardoJiang** [comment]
用了kotlin,应该是有两个库的module名都是library，就会有这个问题

**Comment by gdutxiaoxu** [comment]
已经解决，使用 1.1.0 版本
